#!/usr/bin/env bun
/**
 * Phase 9 accessibility gate — Lighthouse audit.
 *
 * Audits the student dashboard with Lighthouse (desktop preset) and writes the
 * result to docs/PHASE9_A11Y.md. Fails (exit 1) below the Phase 9 targets:
 *   accessibility 100 · best-practices ≥ 95 · performance ≥ 90
 *
 * Usage:
 *   bun run scripts/lighthouse-audit.ts [url]
 *   PHASE9_AUDIT_URL=https://deployed.example bun run scripts/lighthouse-audit.ts
 *
 * Run against a production build (`bun run build && bun run start`) or the
 * deployed URL — dev-server numbers are not representative. For a local
 * production run behind trusted-proxy auth, start the server with
 * AUTH_MODE=trusted-proxy AUTH_PROXY_SECRET=… and pass the trusted headers as
 * PHASE9_AUDIT_HEADERS='{"X-Saint-Elms-Auth-Secret":"…","X-Saint-Elms-User-Id":"student-ananya","X-Saint-Elms-Role":"student"}'.
 */
import { launch } from 'chrome-launcher';
import lighthouse from 'lighthouse';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const TARGETS = { accessibility: 100, 'best-practices': 95, performance: 90 } as const;
const url = process.argv[2] || process.env.PHASE9_AUDIT_URL || 'http://localhost:3000';
const extraHeaders = process.env.PHASE9_AUDIT_HEADERS
  ? (JSON.parse(process.env.PHASE9_AUDIT_HEADERS) as Record<string, string>)
  : undefined;
const outPath = new URL('../docs/PHASE9_A11Y.md', import.meta.url).pathname;

const chrome = await launch({ chromeFlags: ['--headless', '--disable-gpu', '--no-sandbox'] });
try {
  const result = await lighthouse(url, {
    port: chrome.port,
    output: 'json',
    onlyCategories: ['accessibility', 'best-practices', 'performance'],
    formFactor: 'desktop',
    screenEmulation: { mobile: false, width: 1440, height: 900, deviceScaleFactor: 1, disabled: false },
    extraHeaders,
  });
  if (!result) throw new Error('lighthouse returned no result');
  const { lhr } = result;

  const scores = Object.keys(TARGETS).map((category) => ({
    category,
    score: Math.round((lhr.categories[category]?.score ?? 0) * 100),
    target: TARGETS[category as keyof typeof TARGETS],
  }));

  const failingAudits = Object.values(lhr.audits)
    .filter((audit) => audit.score !== null && audit.score < 1 && audit.scoreDisplayMode !== 'notApplicable' && audit.scoreDisplayMode !== 'informative')
    .map((audit) => `| ${audit.id} | ${audit.title} | ${audit.scoreDisplayMode} |`);

  const ok = scores.every((s) => s.score >= s.target);
  const when = new Date().toISOString();

  const markdown = `# Phase 9 — Accessibility & Quality Gate

Generated by \`scripts/lighthouse-audit.ts\` against \`${url}\` at ${when}.

## Lighthouse scores (desktop)

| Category | Score | Target | Verdict |
| --- | ---: | ---: | --- |
${scores.map((s) => `| ${s.category} | ${s.score} | ${s.target} | ${s.score >= s.target ? 'PASS' : 'FAIL'} |`).join('\n')}

${failingAudits.length ? `## Audits below full marks\n\n| Audit | Title | Mode |\n| --- | --- | --- |\n${failingAudits.join('\n')}` : '## Audits below full marks\n\nNone.'}

## WCAG 2.2 hit-list (manual + automated evidence)

| Criterion | Where satisfied | Evidence |
| --- | --- | --- |
| 2.5.7 Dragging movements | Hearth deck: swipe/drag is never required; the 44px persona tab rail and ←/→/Home/End keys are always-available single-pointer and keyboard alternatives | \`src/components/HearthNav.tsx\`, \`src/a11y/a11y.test.tsx\` |
| 2.5.8 Target size (minimum) | Rail tabs, sample prompts, retry buttons, composer send, mobile bar all ≥ 44×44 | class-level assertions in \`src/a11y/a11y.test.tsx\` |
| 2.4.11 Focus not obscured | Deck pins at \`top-16\` leaving the header's focus order untouched; inactive slides are \`inert\` + \`aria-hidden\`; focused panel content scrolls inside the deck, never under sticky chrome | Playwright keyboard pass, 2026-09-01 |
| 3.2.6 Consistent help | Friend (help mechanism) sits in the same position on every viewport: first tab of the pinned rail on desktop, fixed bottom bar on mobile | \`src/components/HearthDeck.tsx\` |
| 2.3.1 Three flashes | \`flicker-fast\` peaks at 2 flashes/sec; \`glow-breathe\` is an opacity wash, not a flash; \`prefers-reduced-motion: reduce\` collapses all animation to ≤0.01ms | \`src/app/globals.css\` |
| 1.4.10 Reflow | Deck is a column flex at <768px; panels scroll internally; no two-dimensional scroll at 320px | Playwright mobile pass, 2026-09-01 |
| 1.4.11 Non-text contrast | Persona identity is iconography + typography in the mariner palette, never hue-only; controls carry borders against \`paper\` | visual review, 2026-09-01 |

## axe-core gate

\`src/a11y/a11y.test.tsx\` renders the Hearth deck (empty / thread / storm / skeleton
states, carousel shell, mobile bar), the student and admin headers, and the quiz
modal into jsdom and fails the suite on any serious/critical axe violation.
Run: \`bun test src/a11y/\`.
`;
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, markdown);

  console.table(scores);
  console.log(`Report written to ${outPath}`);
  if (!ok) {
    console.error('Phase 9 Lighthouse targets not met.');
    process.exit(1);
  }
} finally {
  await chrome.kill();
}
